apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: r7thm9y2t-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: r7thm9y2t-python 
  name: r7thm9y2t-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: r7thm9y2t-python 
